fix: refactor `mouseMoving` function
achareh-co/achar pull request #1
Opened 2022-09-14 18:16 UTC by ramezanidev

2022-09-15 05:42 UTC, ms-fadaei requested changes
سلام رضا جان. روزت بخیر. ممنون بابت مرجح ریکوئست. ممنون میشم یه بررسی داشته باشی روی این مواردی که نوشتم. کلی مرسی 🙏

2022-09-15 05:42 UTC, ms-fadaei commented on src/modules/dom/mouse-moving.ts
> +    return returnHelpers();
یه سوالی برام پیش اومده رضا جان
اینکه `returnHelpers` رو آخر تقریبا همه helper functions صدا می کنی دلیل خاصی داره؟ به نظرم اینکار باعث میشد خود helper functions خیلی خوب به نظر نرسن چون دارن چیزی بر میگردونن که مرتبط به کاری که میکنن نیست

2022-09-15 05:42 UTC, ms-fadaei commented on src/modules/dom/mouse-moving.ts
> +  type cbEvents = (scrollLeft: number) => void;
رضا جان در کل در نظر بگیر که ایپ بهتره که در ابتدای فایل و تو اسکوپ ماژول تعریف بشه. حتی یه تعداد تایپ های اینلاین هم که استفاده کردی بهتره که اینطوری بشه. تایپ های خیلی ساده و premetive اشکالی نداره برای اینلاین شدن

2022-09-15 05:42 UTC, ms-fadaei commented on src/modules/dom/mouse-moving.ts
> +  const events: { [key: string]: null | cbEvents } = {
رضا جان به نظرم اینجا میتونی از Record برای تایپ استفاده کنی. خوانایی بهتری میده

2022-09-15 07:23 UTC, ramezanidev commented on src/modules/dom/mouse-moving.ts
> +    return returnHelpers();
صالح جان اینجا سعی کردم یه جوری پیاده سازی کنم که بشه این مدلی از تابعمون استفاده کرد:

```ts
mouseMoving(el: HTMLElement).on(/* event */).on(/* event */).off(/* event */).destry()
```

فک کنم jq همچین چیزی دیده باشین. اگه آخرشون ریترن نکنم باید این شکلی استفاده بشه

```ts
const mouseevents = mouseMoving(el: HTMLElement);
mouseevents.on(/* event */);
mouseevents.on(/* event */);
mouseevents.off(/* event */)
mouseevents.destry()
```

شما هر پترنی رو که مدنظتون هست و بهتره برای این پروژه من استفاده کنم. کما اینکه پرفرمنسشون فک نکنم فرقی کنه ولی خوانایی کد چرا.

2022-09-15 07:24 UTC, ramezanidev commented on src/modules/dom/mouse-moving.ts
> +  type cbEvents = (scrollLeft: number) => void;
بله حتما رعایت میکنم.

2022-09-15 08:28 UTC, ms-fadaei commented on src/modules/dom/mouse-moving.ts
> +    return returnHelpers();
این الگویی که گفتی بیشتر تو حالتی که کلاس داشته باشیم استفاده میشه. البته کلا این متد اونقدر وابستگی و اینا داره که میشه حتی به حالت کلاسیش ریفکتور کرد

ولی چیزی که الان هست به نظرم حالت دوم به نظر بهتر بیاد. تا حد زیادی وابسته به سلیقه و تجربه و دست خطه

2022-09-15 15:41 UTC, ramezanidev commented
صالح جان مواردی که بودند رو رفعشون کردم.

2022-09-21 09:02 UTC, ms-fadaei approved these changes
ممنون رضا جان. فعلا این رو مرج میکنم اما در آینده باید ریفکتور بشه به کلاس تا بهینه تر و ساختارمند تر باشه. کلی مرسی 🙏

2022-09-21 09:02 UTC, merged